### ISSUE TITLE
Issue with `@signal`'s Cache: `computed` Instances Sharing the Same Cache

### ISSUE THREAD

**Issue by JuerGenie** [proposal-signals/signal-utils#91]
As shown in the screenshots, the `computed` function is only called when the first instance is created and updated, but not for other instances:

![1733986345960](https://github.com/user-attachments/assets/64df22e1-110a-45f7-8d48-0efa0e9c8950)
![1733986360823](https://github.com/user-attachments/assets/3e4865a1-8a4e-4867-9e8f-0535db7b0913)

⬆️ All `content` looks the same (they are the first instance's `content`).

The issue is caused by the following code:

```typescript
// file: signal-utils/src/index.ts

function computedDecorator<Value = any>(
  target: () => Value,
  context: ClassGetterDecoratorContext,
): () => Value {
  /* ... */

  let caches = new WeakMap<typeof target, Signal.Computed<Value>>(); // <- caches target to `Computed` instance, not instance.

  return function (this: unknown) {
    let cache = caches.get(target); // <- always gets the same cache regardless of `this`.
    /* ... */
  };
}
```

This is my solution:

```typescript
function computedDecorator<Value = any>(
  target: () => Value,
  context: ClassGetterDecoratorContext,
): () => Value {
  /* ... */

  let caches = new WeakMap<typeof target, WeakMap<object, Signal.Computed<Value>>>();

  return function (this: unknown) {
    let cache = caches.get(target);
    if (!cache) {
      cache = new WeakMap();
      caches.set(target, cache);
    }
    let effect = cache.get(this as object);
    if (!effect) {
      effect = new Signal.Computed(() => target.call(this));
      cache.set(this as object, effect);
    }

    return effect.get();
  };
}
```

It's work for me.

**Comment by aomarks** [comment]
I can confirm that @JuerGenie's patch above fixed some gnarly bugs I was hitting involving the `@signal` decorator sharing cached values in very mysterious ways. Thank you!

It would be great to get the fix landed -- @JuerGenie any chance you might send your patch as a PR? :)

**Comment by JuerGenie** [comment]
> I can confirm that @JuerGenie's patch above fixed some gnarly bugs I was hitting involving the `@signal` decorator sharing cached values in very mysterious ways. Thank you!
> 
> It would be great to get the fix landed -- @JuerGenie any chance you might send your patch as a PR? :)

Sure, I'll open a PR later today :D
